// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkKaJH7PXTzHJygr_myg3U-IGlh-N3ns',
    appId: '1:249723010235:web:78a82d50a68237cf0b3d9e',
    messagingSenderId: '249723010235',
    projectId: 'prayer-room-locator',
    authDomain: 'prayer-room-locator.firebaseapp.com',
    storageBucket: 'prayer-room-locator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-twf40fOacK6tNuZxDt1wHo_5le5fDKc',
    appId: '1:249723010235:android:9b45a19112ffa4260b3d9e',
    messagingSenderId: '249723010235',
    projectId: 'prayer-room-locator',
    storageBucket: 'prayer-room-locator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWY39M70d0j6JOygeqB5GSvJKlVagmexU',
    appId: '1:249723010235:ios:37151c51434b40560b3d9e',
    messagingSenderId: '249723010235',
    projectId: 'prayer-room-locator',
    storageBucket: 'prayer-room-locator.appspot.com',
    iosBundleId: 'com.example.prayerRoomLocator',
  );
}
